"""add file meta

Revision ID: 7de82627789f
Revises: f59b43303f4c
Create Date: 2025-11-24 13:43:02.767051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de82627789f'
down_revision: Union[str, Sequence[str], None] = 'f59b43303f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_file_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('store_type', sa.Enum('RUSTFS', 'MINIO', name='filestore'), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('rustfs_key', sa.String(), nullable=True),
    sa.Column('minio_key', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['m_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('minio_key'),
    sa.UniqueConstraint('rustfs_key'),
    sa.UniqueConstraint('store_type', 'minio_key', name='file_meta_uniq_2'),
    sa.UniqueConstraint('store_type', 'rustfs_key', name='file_meta_uniq_1')
    )
    op.create_index(op.f('ix_m_file_meta_file_type'), 'm_file_meta', ['file_type'], unique=False)
    op.create_index(op.f('ix_m_file_meta_id'), 'm_file_meta', ['id'], unique=False)
    op.create_index(op.f('ix_m_file_meta_store_type'), 'm_file_meta', ['store_type'], unique=False)
    op.create_index(op.f('ix_m_file_meta_uploaded_by'), 'm_file_meta', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_m_file_meta_uploaded_by'), table_name='m_file_meta')
    op.drop_index(op.f('ix_m_file_meta_store_type'), table_name='m_file_meta')
    op.drop_index(op.f('ix_m_file_meta_id'), table_name='m_file_meta')
    op.drop_index(op.f('ix_m_file_meta_file_type'), table_name='m_file_meta')
    op.drop_table('m_file_meta')
    # ### end Alembic commands ###
