"""add created and updated on user

Revision ID: d42b285e41af
Revises: facead4fbb90
Create Date: 2025-09-13 01:38:26.359458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42b285e41af'
down_revision: Union[str, Sequence[str], None] = 'facead4fbb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('m_users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('m_users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('m_users', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('m_users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_users', 'updated_at')
    op.drop_column('m_users', 'updated_by')
    op.drop_column('m_users', 'created_at')
    op.drop_column('m_users', 'created_by')
    op.drop_column('m_users', 'is_active')
    # ### end Alembic commands ###
