"""add api permissions

Revision ID: f59b43303f4c
Revises: d42b285e41af
Create Date: 2025-10-08 18:43:40.124372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59b43303f4c'
down_revision: Union[str, Sequence[str], None] = 'd42b285e41af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_apis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD', 'ALL', name='httpmethodenum'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('act', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('version > 0', name='api_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method', 'version', 'act', 'name', name='api_uniq_1')
    )
    op.create_index(op.f('ix_m_apis_act'), 'm_apis', ['act'], unique=False)
    op.create_index(op.f('ix_m_apis_id'), 'm_apis', ['id'], unique=False)
    op.create_index(op.f('ix_m_apis_method'), 'm_apis', ['method'], unique=False)
    op.create_index(op.f('ix_m_apis_version'), 'm_apis', ['version'], unique=False)
    op.create_table('m_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='profile_uniq_1')
    )
    op.create_index(op.f('ix_m_profiles_id'), 'm_profiles', ['id'], unique=False)
    op.create_table('r_api_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['m_apis.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['m_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id', 'profile_id', name='api_permission_uniq_1')
    )
    op.create_index(op.f('ix_r_api_permission_api_id'), 'r_api_permission', ['api_id'], unique=False)
    op.create_index(op.f('ix_r_api_permission_id'), 'r_api_permission', ['id'], unique=False)
    op.create_index(op.f('ix_r_api_permission_profile_id'), 'r_api_permission', ['profile_id'], unique=False)
    op.create_table('r_user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['m_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['m_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'profile_id', name='user_profile_uniq_1')
    )
    op.create_index(op.f('ix_r_user_profile_id'), 'r_user_profile', ['id'], unique=False)
    op.create_index(op.f('ix_r_user_profile_profile_id'), 'r_user_profile', ['profile_id'], unique=False)
    op.create_index(op.f('ix_r_user_profile_user_id'), 'r_user_profile', ['user_id'], unique=False)
    op.create_unique_constraint('user_uniq_1', 'm_users', ['username'])
    op.create_unique_constraint('user_uniq_2', 'm_users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_uniq_2', 'm_users', type_='unique')
    op.drop_constraint('user_uniq_1', 'm_users', type_='unique')
    op.drop_index(op.f('ix_r_user_profile_user_id'), table_name='r_user_profile')
    op.drop_index(op.f('ix_r_user_profile_profile_id'), table_name='r_user_profile')
    op.drop_index(op.f('ix_r_user_profile_id'), table_name='r_user_profile')
    op.drop_table('r_user_profile')
    op.drop_index(op.f('ix_r_api_permission_profile_id'), table_name='r_api_permission')
    op.drop_index(op.f('ix_r_api_permission_id'), table_name='r_api_permission')
    op.drop_index(op.f('ix_r_api_permission_api_id'), table_name='r_api_permission')
    op.drop_table('r_api_permission')
    op.drop_index(op.f('ix_m_profiles_id'), table_name='m_profiles')
    op.drop_table('m_profiles')
    op.drop_index(op.f('ix_m_apis_version'), table_name='m_apis')
    op.drop_index(op.f('ix_m_apis_method'), table_name='m_apis')
    op.drop_index(op.f('ix_m_apis_id'), table_name='m_apis')
    op.drop_index(op.f('ix_m_apis_act'), table_name='m_apis')
    op.drop_table('m_apis')
    # ### end Alembic commands ###
