"""alter username field

Revision ID: facead4fbb90
Revises: 41e49900d77a
Create Date: 2025-09-09 08:56:53.635943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'facead4fbb90'
down_revision: Union[str, Sequence[str], None] = '41e49900d77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_users', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('m_users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('m_users', 'username')
    # ### end Alembic commands ###
